version: '3.3'
services: 
    eureka-server:
        image: mani30899/eureka-server:1.0
        ports: 
            - "8761:8761"
        networks: 
            - app-network
    
    menu-item-service:
        image: mani30899/menu-item-service:1.0
        ports: 
            - "5100:5100"
        environment: 
            EUREKA_HOST: eureka-server
        depends_on: 
            - eureka-server
        networks: 
            - app-network

    coupon-service:
        image: mani30899/coupon-service:1.0
        ports: 
            - "5200:5200"
        environment: 
            EUREKA_HOST: eureka-server
        depends_on: 
            - eureka-server
        networks: 
            - app-network

  
        

networks: 
    app-network:
        
